### ISSUE TITLE
Upgrade to Hyper 0.12

### ISSUE THREAD

**Issue by jeffvandyke** [hjr3/hyper-timeout#5]
Hyper 0.12 is a breaking change ([see release notes](https://github.com/hyperium/hyper/releases/tag/v0.12.0)), but it's becoming necessary as there's a dependency path through hyper-tls 0.1 (and 0.2) to native-tls 0.1, which depends on openssl 0.9, which is breaking on a growing number of Linux systems ([see this issue](https://github.com/sfackler/rust-openssl/issues/994)).

**Comment by hjr3** [comment]
Thanks. I will take a look at this tomorrow.

**Comment by jeffvandyke** [comment]
As something to keep an eye on, Hyper is working on 0.13, but it's uncertain when they'll be finished:[Hyper 0.13 milestone](https://github.com/hyperium/hyper/milestone/5)

**Comment by hjr3** [comment]
I took a look at this and see what needs to be done. I am working through some of the details. I will try and have an update in a few days.

**Comment by jeffvandyke** [comment]
Awesome. This might allow a simple decision on how to bring [Rincon](https://github.com/innoave/rincon)'s Hyper version up to date ([upgrade issue](https://github.com/innoave/rincon/issues/11)).

**Comment by hjr3** [comment]
https://github.com/hjr3/hyper-timeout/pull/6 compiles and tests are working. I will need to review and do some more testing before I push a release.

**Comment by jeffvandyke** [comment]
Woohoo, very impressive turnaround time, hope the finish goes well!

**Comment by hjr3** [comment]
https://crates.io/crates/hyper-timeout `0.2.0` has been released! Let me know if have any issues.
