### ISSUE TITLE
Support for hyper 0.13

### ISSUE THREAD

**Issue by augustocdias** [hjr3/hyper-timeout#9]
Is there any work done to support hyper 0.13?

**Comment by hjr3** [comment]
Yes, I will be releasing a version that works with hyper 0.13 soon.

**Comment by hjr3** [comment]
https://github.com/hjr3/hyper-timeout/pull/10 is up if you want to check it out. I have some clean up to do. I plan on merging this in the next few days.

**Comment by hjr3** [comment]
https://github.com/hjr3/hyper-timeout/releases/tag/0.3.0

**Comment by augustocdias** [comment]
Nice! I've been trying out already.
I think you forgot to publish to crates.io

**Comment by hjr3** [comment]
Thanks, should be on crates.io now https://crates.io/crates/hyper-timeout
